export const GET_REQUEST_ADMIN_SIDE = "GET_REQUEST_ADMIN_SIDE";
export const GET_REQUEST_SUCCESS_ADMIN_SIDE = "GET_REQUEST_SUCCESS_ADMIN_SIDE";
export const GET_REQUEST_FAILURE_ADMIN_SIDE = "GET_REQUEST_FAILURE_ADMIN_SIDE";

export const PATCH_REQUEST_ADMIN_SIDE = "GET_REQUEST_ADMIN_SIDE";
export const PATCH_REQUEST_SUCCESS_ADMIN_SIDE = "GET_REQUEST_SUCCESS_ADMIN_SIDE";
export const PATCH_REQUEST_FAILURE_ADMIN_SIDE = "GET_REQUEST_FAILURE_ADMIN_SIDE";