export const GET_REQUEST_USER = "GET_REQUEST_USER";
export const GET_REQUEST_SUCCESS_USER = "GET_REQUEST_SUCCESS_USER";
export const GET_REQUEST_FAILURE_USER = "GET_REQUEST_FAILURE_USER";
export const  DELETE_USER_DATA = " DELETE_USER_DATA"